Filled in bash script and syn script

diff --git a/5/doit b/5/doit
--- a/5/doit
+++ b/5/doit
@@ -1,18 +1,20 @@
 #!/usr/bin/env bash
 
-#make directories needed if they don't exist
-if [ ! -s vectors ]; then
-  mkdir vectors
-fi
+synop_lib="/nfs/guille/a1/cadlibs/synop_lib/SAED_EDK90nm/Digital_Standard_Cell_Library/verilog"
 
-if [ ! -s reports]; then
-  mkdir reports
-fi
+#make directories needed if they don't exist
+dirs = "bin logs reports sdfout vectors vlogout"
+
+for dir in $dirs
+do
+  if [ ! -d $dir ] ; then
+    mkdir $dir
+  fi
+done
 
 #remove previous results from /vectors and /reports
-#rm.....
-#rm.....
-#rm.....
+rm -f /reports/*
+rm -f /vectors/output_*
 
 #check for work directory and make if necessary
 if [ ! -d "work" ] ; then
@@ -27,25 +29,32 @@ vlog tb_src/tb.sv
 vsim tb -do dofile -quiet -c -t 1ps
 
 #rename the output_data
-
-#remove the old output_data file
+mv vectors/output_data vectors/output_data_rtl
 
 #diff output_data and golden_data
+! diff vectors/output_data_rl vectors/golden_data --brief > reports/rtl_miscompares
 
 #report the results
+if [ $? == 0 ] ; then
+  echo -n "no "
+fi
+echo "errors detected in rtl output"
 
 #compile synthesis library into work if needed
+if ! grep --quiet AND2X1.v ./work/_info ; then
+  vlog $synop_lib/*  -work work
+fi
 
 #synthesize the design using dc_syn and redirect output to the logfile
 if [ -s "bin/dc_syn" ] ; then
-	dc_shell-xg-t -f bin/dc_syn > logs/synth_log
+  dc_shell-xg-t -f bin/dc_syn > logs/synth_log
 fi
 
 #check for latches in synthesized design
-##grep.....
-
-#check for errors in synthesis from latches being included
-#if latches are found, report it
+if ! grep "LN* | LA*" reports/cells_used ; then
+  echo -n "no "
+fi
+echo "latches found in output"
 
 #fix missing timing parameter in sdf file
 sed '/(HOLD (posedge RSTB)/d' < sdfout/gcd.gate.sdf  > sdfout/$$tempfile
@@ -59,22 +68,29 @@ vlog vlogout/gcd.gate.v  -work work
 vsim tb -do dofile  +nowarnTFMPC -quiet -c -t 1ps
 
 #rename the output_data
-mv vectors/output_data vectors/output_data.gate
-
-#remove the old output_data file
+mv vectors/output_data vectors/output_data_gate
 
 #diff output_data and golden_data
+! diff vectors/output_data_gate vectors/golden_data --brief > reports/gate_miscompares
 
 #report the results
+if [ $? == 0 ] ; then
+  echo -n "no "
+fi
+echo "errors detected in gate output"
 
 #simulate the gate-level gcd with the sdf file
 vsim tb -do dofile +nowarnTFMPC -quiet -c -sdfmax /tb/gcd_0=sdfout/gcd.gate.sdf -t 1ps  +nowarn3448
 
 #rename the output_data
-
-#remove the old output_data file
+mv vectors/output_data vectors/output_data_gate_sdf
 
 #diff output_data and golden_data
+! diff vectors/output_data_gate_sdf vectors/golden_data --brief > reports/gate_sdf_miscompares
 
 #report the results
+if [ $? == 0 ] ; then
+  echo -n "no "
+fi
+echo "errors detected in sdf/gate output"
 
